name: rag-chatbot
dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain
      - langchain-huggingface
      - langchain-community
      - faiss-cpu
      - openai
      - sentence-transformers
      - streamlit
      - transformers
      - pymupdf
      - ipywidgets
      - notebook
      - tqdm