name: her2-rag-env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - langchain
      - langchain-community
      - langchain-huggingface
      - faiss-cpu
      - sentence-transformers
      - transformers
      - accelerate
      - evaluate
      - pandas
      - scikit-learn
      - bert-score  # optional for semantic evaluation
